### ISSUE TITLE
Add service disruption banner to PSM UI for Noble USDC and Kava USDT core eval deployment

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-psm#108]
We need to add a banner to PSM UI to notify users of a possible service disruption when the Noble USDC and Kava USDT PSMs are added via core eval at 9:30AM and 10am Pacific on Wednesday November 1st.

Description of the Design

Show notice from ASAP -> 11am Pacific Wednesday 1st Nov

'Notice: PSM functionality will shortly be updated as per Proposal 59 (Enabled Noble USDC PSM) and Proposal 60 (Enable Kava USDT PSM) - from 2023-11-01 | 09:30AM - 10:30AM Pacific. While we do not anticipate an outage we do expect a slow-down for several minutes.'

**Comment by samsiegart** [comment]
Launch was successful, banners removed now
