### ISSUE TITLE
dapp-psm  - Message banners on inter.trade to sets the expectation for an impending mainnet upgrade

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/dapp-psm#113]
We need to add a banner to PSM UI to notify users of a service disruption when the upgrade 12 occurs. 

Description of the Design

Show notice from ASAP -> 4pm Pacific Monday 20th Nov

'A chain upgrade (Proposal 63 - Agoric Upgrade 12) is planned to take place between 2023-11-20 | 02:10PM - 03:10PM Pacific. The PSM UI will not be functional during this time'

**Comment by samsiegart** [comment]
Banner is up now

**Comment by otoole-brendan** [comment]
@samsiegart mea culpa - I missed the fact that the upgrade wouldn't happen right after voting ends like core evals. Could you update banner message to reflect that: 'A chain upgrade (Proposal 63 - Agoric Upgrade 12) is planned to take place on 2023-11-21 | 09:00AM - 10:00PM Pacific. The PSM UI will not be functional during this time'

**Comment by samsiegart** [comment]
Updated
