### ISSUE TITLE
Add IST balance and 'Get IST' button to smart wallet provision dialog

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-psm#124]
https://github.com/Agoric/dapp-psm/issues/116 adds the auto-wallet provisioning flow to the PSM.

This ticket improves the UX but adding two features to the dialog:

1. The user's IST balance
2. A 'Get IST' button that launches Leap Elements modal for easy IST onboarding (to provision smart wallet)

As part of this dialog change - 'Proceed' should not be illuminated or clickable until the user has at least sufficient IST balance to cover wallet-provisioning (1IST). 

The Leap Elements modal should include the Kado module to ensure users with no crypto assets have a means to buy IST using fiat/credit card

Design

Match to dapp-inter dialog per https://github.com/Agoric/dapp-inter/pull/227#issuecomment-1969875810
<img width="683" alt="image" src="https://github.com/Agoric/dapp-psm/assets/93355546/85164c0a-971e-4fdc-ba8d-9141ee8e0b58">

**Comment by samsiegart** [comment]
completed: https://github.com/Agoric/dapp-psm/pull/128
