### ISSUE TITLE
Enable service disruption banner on dapp-psm for Kryha Mainnet deployment

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-psm#99]
We need to add a banner to PSM UI to notify users of a imminent possible outage with walletFactory core eval deployment

Use https://github.com/Agoric/dapp-psm/pull/94 as guidance

Description of the Design

Notice: New contract functionality will soon be upgraded as per Proposal 53 (KREAd-rc1 to Mainnet). We do not anticipate an interruption of service but transactions may be delayed around the upgrade time on Oct 01, 2023 1:18:31 PM PDT

**Comment by ivanlei** [comment]
<img width="1070" alt="Screenshot 2023-10-01 at 1 44 34 PM" src="https://github.com/Agoric/dapp-psm/assets/1002798/d8e4f38a-76a4-484a-af4d-24963f9f3f8f">
